### PR TITLE
Update notebooks

### PR DESCRIPTION
**Pull request by thenom**
Just thought i would submit this back to you guys.  Couldn't get the one in master to work properly with the latest libraries.  This one seems to work fine for me now but let me know if you need anymore from me for this PR.

### CODE REVIEW

**Comment by larsll** [comment]
@thenom - what exactly was the problem you faced? I see it now uses conda; but not all enviroments here will likely have conda installed...

**Comment by thenom** [comment]
@larsll - your right it does have conda installed, i am just using it to install the geos package.  There was a few dependency issues due to package updates from what i remember around the tensorflow gfile library package being deprecated\moved so had to do a bit of reshuffling.  I think it was similar to this:

https://github.com/tensorflow/tensorflow/issues/31315

**Comment by larsll** [comment]
@thenom - the books have now received a quite substantial upgrade (compatible with the new way of loading files straight from S3). Please check what of your changes are still applicable. 

The books are written with `tensorflow==1.15.4`, see e.g. `docker/Dockerfile.cpu-tf`

**Review by larsll — CHANGES_REQUESTED** [review]
Merge in latest changes, review what changes are still required.

**Comment by larsll** [comment]
Closing as inactive. Since this was open significant changes have been made.

**Pull request closed without merging**
